apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: userapp-admin-role
rules:
- apiGroups:
  - sub.userapp.hjjzs.xyz
  resources:
  - users/changepass
  - users/changerole
  - users/disUser
  - users
  verbs:
  - '*'

- apiGroups:
  - subresources.kubevirt.io
  resources:
  - virtualmachineinstances/console
  - virtualmachineinstances/vnc
  verbs:
  - '*'

- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - '*'

- apiGroups:
  - userapp.hjjzs.xyz
  resources:
  - users
  verbs:
  - '*'