apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: userapp-user-role
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - '*'

- apiGroups:
  - sub.userapp.hjjzs.xyz
  resources:
  - users/changepass
  verbs:
  - '*'

- apiGroups:
  - subresources.kubevirt.io
  resources:
  - virtualmachineinstances/console
  - virtualmachineinstances/vnc
  - virtualmachines/addvolume
  - virtualmachines/removevolume
  - virtualmachines/migrate
  verbs:
  - '*'
  
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'




